<a href="https://colab.research.google.com/github/Diggi14/project_Property2/blob/main/loc_generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/Diggi14/project_Property2.git

Cloning into 'project_Property2'...
remote: Enumerating objects: 55, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 55 (delta 26), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (55/55), 3.45 MiB | 6.29 MiB/s, done.
Resolving deltas: 100% (26/26), done.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('/content/project_Property2/model_trainer.csv')

In [4]:
df['LOCALITY_WO_CITY'].unique()

array(['Sector 84', 'Sector 81', 'Sector 112', 'Sector 104', 'Sector 74',
       'Sector 102', 'Sector 60', 'Sector 66', 'Sector 110', 'Sector 109',
       'Sector 65', 'Sector 37D', 'Sector 113 Gurgaon', 'Sector 111',
       'Sushant Lok Phase 3', 'Sector 62', 'Sector 57', 'Sector 59',
       'Sector 37C', 'Sector 53', 'Sector 28', 'Sector 67', 'Sector 54',
       'Sector 106', 'Sector 108', 'Sector 61', 'DLF Phase 2',
       'Sector 82', 'South City 2', 'DLF Phase 5', 'Sector 90',
       'Sector 103', 'Sector 63', 'Sector 107', 'Malibu Town',
       'Sector 63A', 'Uppals Southend', 'Sector 68', 'Sector 48',
       'Sector 50', 'Sector 36A', 'Sector 110 A', 'Sector 51',
       'Sector 31', 'Palam Vihar', 'Sector 23', 'Sector 46', 'Sector 45',
       'Sector 67A', 'Sector-33 Sohna', 'Sohna', 'Sector 36 Sohna',
       'Sector 71', 'Sector 82A', 'Sector 14', 'DLF Phase 4', 'Sector 72',
       'Sector 3', 'Sector 85', 'Sector 49', 'Sector-2 Sohna',
       'Nirvana Country', 'Sector 70', 'Sector 88B', 'Sector 88A',
       'Sector 99', 'Sector 99A', 'Sector 92', 'Sector 69', 'Gwal Pahari',
       'Sushant Lok Phase 1', 'Sector 83', 'MG Road', 'Sector 70A',
       'Sector 79', 'Sector 89', 'Sector 42', 'Sector 52', 'Sector 86',
       'DLF Phase 1', 'Sector 47', 'Sector 26', 'Sushant Lok Phase 2',
       'Sector 56', 'DLF Phase 3', 'Ardee City', 'Sector 27', 'Sector 55',
       'Sector 89 A', 'Sector 93', 'Ansal Plaza', 'Heritage City',
       'Sushant Lok', 'Sector 43', 'South City 1', 'Sector 22',
       'Sector 95', 'Mayfield Garden', 'Rosewood', 'Suncity', 'Sector 76',
       'Sector 4', 'Sector 15 Part 2', 'Valley View Estate', 'Sector 1',
       'Shyam Kunj', 'sector 58', 'Sector 91', 'Sohna Road',
       'Vigyan Vihar', 'New Palam Vihar', 'DLF CITY', 'Sector 33',
       'Sector 73', 'Golf Course Ext Road', 'Bhondsi', 'Greenwood City',
       'Sector 10A', 'New golf course ext road', 'Sector 39', 'Sector 77',
       'Subhash Nagar', 'Sector 30', 'New Colony', 'Sector 15',
       'Sector 40', 'Rattan Garden', 'Surat Nagar 1',
       'Udyog Vihar Industrial Area Phase 6', 'Laxman Vihar',
       'Dharam Colony', 'Sector 5', 'Sector 78', 'Sector 7 Extension',
       'Sector 9', 'Sector 23A', 'Mayfield garden', 'Sector 38',
       'Westerlies', 'Sector 2', 'Sector 95A', 'Sector 41', 'sector 28',
       'Southern Peripheral Road', 'South City', 'Sector 17', 'Samaspur',
       'Kadarpur', 'sector 83', 'Pataudi Road', 'New Palam Vihar Phase 1',
       'Sai Kunj', 'Sector 21', 'Sector 9A', 'Sector 17B', 'Chakkarpur',
       'Sushant Lok 3 Extension', 'Sector 7', 'Ashok Vihar Phase 1',
       'Sector-5 Sohna', 'Bissar', 'sector 62', 'Farrukh Nagar',
       'Sector 80', 'Dayanand Colony', 'Phase 2 Sushant Lok 3',
       'Sector 17C', 'Cyber City', 'Patel Nagar', 'Ramgarh', 'Sector 64',
       'Jharsa', 'Civil Lines', 'Sector 10', 'Sector 22B', 'Shivpuri',
       'Gurgaon', 'Dwarka Expressway', 'Palam Vihar Extension',
       'Jyoti Park', 'Sector 1A'], dtype=object)

In [5]:
import requests, time, json

sectors = df['LOCALITY_WO_CITY'].unique()
headers = {"User-Agent": "GurgaonMapper/1.0"}
results = {}

for sector in sectors:
    r = requests.get(
        "https://nominatim.openstreetmap.org/search",
        params={"q": f"{sector}, Gurugram, Haryana, India",
                "format": "json", "limit": 1},
        headers=headers
    )
    data = r.json()
    if data:
        bb = data[0]["boundingbox"]  # [south, north, west, east]
        results[sector] = {
            "south": float(bb[0]), "north": float(bb[1]),
            "west":  float(bb[2]), "east":  float(bb[3]),
            "lat":   float(data[0]["lat"]),
            "lon":   float(data[0]["lon"]),
        }
        print(f"[OK] {sector}: SW({bb[0]},{bb[2]}) NE({bb[1]},{bb[3]})")
        results[sector] = f"SW({bb[0]},{bb[2]}) NE({bb[1]},{bb[3]})"
    time.sleep(1)

with open("sector_bbox.json", "w") as f:
    json.dump(results, f, indent=2)

[OK] Sector 84: SW(28.3992344,76.9547099) NE(28.4171845,76.9728238)
[OK] Sector 81: SW(28.3810248,76.9358092) NE(28.3955282,76.9566384)
[OK] Sector 112: SW(28.5133462,77.0105771) NE(28.5348138,77.0234394)
[OK] Sector 104: SW(28.4686072,76.9808303) NE(28.4931639,77.0085706)
[OK] Sector 74: SW(28.4008281,77.0000093) NE(28.4240826,77.0196986)
[OK] Sector 102: SW(28.4678764,76.9607315) NE(28.4860356,76.9808303)
[OK] Sector 60: SW(28.3785617,77.0778276) NE(28.4185617,77.1178276)
[OK] Sector 66: SW(28.3774292,77.0338823) NE(28.4174292,77.0738823)
[OK] Sector 110: SW(28.4953561,77.0081750) NE(28.5187849,77.0269322)
[OK] Sector 109: SW(28.5013412,76.9948373) NE(28.5184844,77.0186166)
[OK] Sector 65: SW(28.3939999,77.0589847) NE(28.4122793,77.0805790)
[OK] Sector 37D: SW(28.4299891,76.9602355) NE(28.4615642,76.9842180)
[OK] Sector 113 Gurgaon: SW(28.5187849,77.0185792) NE(28.5362180,77.0340512)
[OK] Sector 111: SW(28.5144708,77.0251671) NE(28.5300656,77.0424046)
[OK] Sushant Lok Phase 3: SW(28.4143567,77.0709427) NE(28.4272426,77.0911594)
[OK] Sector 62: SW(28.3994698,77.0746581) NE(28.4173299,77.0923553)
[OK] Sector 57: SW(28.4122793,77.0648143) NE(28.4306451,77.0912480)
[OK] Sector 59: SW(28.3830162,77.0866682) NE(28.4230162,77.1266682)
[OK] Sector 37C: SW(28.4424744,76.9782526) NE(28.4544427,76.9972285)
[OK] Sector 53: SW(28.4312887,77.0876834) NE(28.4502537,77.1053206)
[OK] Sector 28: SW(28.4679062,77.0715635) NE(28.4814775,77.0946320)
[OK] Sector 67: SW(28.3664052,77.0398046) NE(28.4064052,77.0798046)
[OK] Sector 54: SW(28.4313367,77.0994329) NE(28.4504499,77.1220533)
[OK] Sector 106: SW(28.4931639,76.9854207) NE(28.5144465,77.0081750)
[OK] Sector 108: SW(28.5071706,76.9706359) NE(28.5212528,76.9991059)
[OK] Sector 61: SW(28.3910188,77.0763685) NE(28.4310188,77.1163685)
[OK] DLF Phase 2: SW(28.4786554,77.0716828) NE(28.4942383,77.0947450)
[OK] Sector 82: SW(28.3861541,76.9509035) NE(28.3992344,76.9674154)
[OK] South City 2: SW(28.4188292,77.0438659) NE(28.4189300,77.0439752)
[OK] DLF Phase 5: SW(28.5019932,77.0938062) NE(28.5052675,77.0966821)
[OK] Sector 90: SW(28.4000485,76.9276481) NE(28.4135610,76.9453919)
[OK] Sector 103: SW(28.4817885,76.9720448) NE(28.5071706,76.9994099)
[OK] Sector 63: SW(28.3764476,77.0664980) NE(28.4164476,77.1064980)
[OK] Sector 107: SW(28.4984432,76.9620491) NE(28.5157991,76.9854207)
[OK] Malibu Town: SW(28.4194922,77.0392329) NE(28.4279551,77.0546677)
[OK] Sector 63A: SW(28.4172746,77.0910767) NE(28.4314754,77.1053206)
[OK] Sector 68: SW(28.3688970,77.0259859) NE(28.4088970,77.0659859)
[OK] Sector 48: SW(28.3904903,77.0194627) NE(28.4304903,77.0594627)
[OK] Sector 50: SW(28.4065560,77.0518744) NE(28.4265483,77.0746581)
[OK] Sector 36A: SW(28.4002285,76.9519998) NE(28.4402285,76.9919998)
[OK] Sector 110 A: SW(28.4953561,77.0081750) NE(28.5187849,77.0269322)
[OK] Sector 51: SW(28.4205318,77.0572988) NE(28.4368753,77.0754687)
[OK] Sector 31: SW(28.4462503,77.0419032) NE(28.4595874,77.0566718)
[OK] Palam Vihar: SW(28.4911464,77.0146077) NE(28.5050072,77.0285830)
[OK] Sector 23: SW(28.5025964,77.0417925) NE(28.5166427,77.0671624)
[OK] Sector 46: SW(28.4276614,77.0492887) NE(28.4438734,77.0673151)
[OK] Sector 45: SW(28.4368753,77.0581972) NE(28.4524700,77.0759032)
[OK] Sector 67A: SW(28.4677037,77.0179221) NE(28.4814427,77.0320237)
[OK] Sector-33 Sohna: SW(28.2005681,77.0031377) NE(28.4465841,77.2418683)
[OK] Sohna: SW(28.2005681,77.0031377) NE(28.4465841,77.2418683)
[OK] Sector 36 Sohna: SW(28.4086456,77.1011878) NE(28.4281810,77.1182005)
[OK] Sector 71: SW(28.4005528,77.0160432) NE(28.4200704,77.0308750)
[OK] Sector 82A: SW(28.3790600,76.9566384) NE(28.3916719,76.9728308)
[OK] Sector 14: SW(28.4537840,77.0271827) NE(28.4937840,77.0671827)
[OK] DLF Phase 4: SW(28.4918548,77.0937304) NE(28.4919548,77.0938304)
[OK] Sector 72: SW(28.4005528,77.0233009) NE(28.4242889,77.0402781)
[OK] Sector 3: SW(28.4807364,77.0109259) NE(28.5050072,77.0287828)
[OK] Sector 85: SW(28.3955282,76.9453919) NE(28.4120177,76.9608587)
[OK] Sector 49: SW(28.4013433,77.0403237) NE(28.4208461,77.0589847)
[OK] Sector-2 Sohna: SW(28.2005681,77.0031377) NE(28.4465841,77.2418683)
[OK] Nirvana Country: SW(28.4081977,77.0574900) NE(28.4217797,77.0733666)
[OK] Sector 70: SW(28.3747261,77.0023138) NE(28.4147261,77.0423138)
[OK] Sector 88B: SW(28.4220223,76.9338495) NE(28.4620223,76.9738495)
[OK] Sector 88A: SW(28.4279229,76.9485789) NE(28.4391412,76.9612918)
[OK] Sector 99: SW(28.4445549,76.9428585) NE(28.4845549,76.9828585)
[OK] Sector 99A: SW(28.4354059,76.9310278) NE(28.4754059,76.9710278)
[OK] Sector 92: SW(28.4012233,76.8993916) NE(28.4181216,76.9276849)
[OK] Sector 69: SW(28.3760701,77.0172311) NE(28.4160701,77.0572311)
[OK] Gwal Pahari: SW(28.4275976,77.1416178) NE(28.4376741,77.1554252)
[OK] Sushant Lok Phase 1: SW(28.4483435,77.0747305) NE(28.4611143,77.0892942)
[OK] Sector 83: SW(28.3862180,76.9608587) NE(28.4051340,76.9825179)
[OK] MG Road: SW(28.4766764,77.0646579) NE(28.4772817,77.0678738)
[OK] Sector 70A: SW(28.3646684,77.0020391) NE(28.4046684,77.0420391)
[OK] Sector 79: SW(28.4950144,77.0687536) NE(28.5119073,77.0916743)
[OK] Sector 89: SW(28.4072042,76.9355611) NE(28.4279650,76.9547099)
[OK] Sector 42: SW(28.4492302,77.0952570) NE(28.4679478,77.1220533)
[OK] Sector 52: SW(28.4296677,77.0673151) NE(28.4473152,77.0913054)
[OK] Sector 86: SW(28.3880122,76.9313357) NE(28.4072042,76.9509035)
[OK] DLF Phase 1: SW(28.4665171,77.0801940) NE(28.4865171,77.1001940)
[OK] Sector 47: SW(28.4171357,77.0370191) NE(28.4346743,77.0584137)
[OK] Sector 26: SW(28.4679478,77.0937546) NE(28.4850694,77.1106768)
[OK] Sushant Lok Phase 2: SW(28.4588488,77.0731100) NE(28.4679529,77.0838476)
[OK] Sector 56: SW(28.4172746,77.0910767) NE(28.4314754,77.1053206)
[OK] DLF Phase 3: SW(28.4918548,77.0937304) NE(28.4919548,77.0938304)
[OK] Ardee City: SW(28.4355804,77.0709692) NE(28.4463884,77.0834464)
[OK] Sector 27: SW(28.4446566,77.0639505) NE(28.4846566,77.1039505)
[OK] Sector 55: SW(28.4192579,77.1051935) NE(28.4314188,77.1184055)
[OK] Sector 89 A: SW(28.4072042,76.9355611) NE(28.4279650,76.9547099)
[OK] Sector 93: SW(28.4084230,76.9241277) NE(28.4207947,76.9416780)
[OK] Ansal Plaza: SW(28.5107295,77.0410333) NE(28.5118915,77.0425578)
[OK] Heritage City: SW(28.4797555,77.0757007) NE(28.4848935,77.0798901)
[OK] Sushant Lok: SW(28.4706134,77.0797627) NE(28.4707134,77.0798627)
[OK] Sector 43: SW(28.4473152,77.0741115) NE(28.4631626,77.0994329)
[OK] South City 1: SW(28.4187919,77.0439742) NE(28.4188928,77.0440835)
[OK] Sector 22: SW(28.4970534,77.0575714) NE(28.5114759,77.0714703)
[OK] Sector 95: SW(28.3949443,76.8914892) NE(28.4349443,76.9314892)
[OK] Mayfield Garden: SW(28.4165009,77.0553416) NE(28.4265483,77.0685475)
[OK] Rosewood: SW(28.4049893,77.0513496) NE(28.4155534,77.0589847)
[OK] Suncity: SW(28.4331657,77.1368380) NE(28.4379444,77.1383352)
[OK] Sector 76: SW(28.3710112,76.9700243) NE(28.4110112,77.0100243)
[OK] Sector 4: SW(28.4688345,77.0019787) NE(28.4807364,77.0179221)
[OK] Sector 15 Part 2: SW(28.3579916,77.0698301) NE(28.3611956,77.0698535)
[OK] Valley View Estate: SW(28.4334343,77.1347453) NE(28.4379960,77.1376325)
[OK] Sector 1: SW(28.3485815,76.9400968) NE(28.3716597,76.9592194)
[OK] sector 58: SW(28.4086456,77.1011878) NE(28.4281810,77.1182005)
[OK] Sector 91: SW(28.3937778,76.9086172) NE(28.4084230,76.9313357)
[OK] Sohna Road: SW(28.4549006,77.0264690) NE(28.4592938,77.0292560)
[OK] DLF CITY: SW(28.4611143,77.0798273) NE(28.4677035,77.0896737)
[OK] Sector 33: SW(28.4262264,77.0101187) NE(28.4478757,77.0370191)
[OK] Sector 73: SW(28.4008164,77.0092134) NE(28.4220077,77.0233009)
[OK] Bhondsi: SW(28.3304798,77.0418737) NE(28.3704798,77.0818737)
[OK] Greenwood City: SW(28.4408105,77.0581972) NE(28.4500074,77.0654085)
[OK] Sector 10A: SW(28.4358808,76.9972285) NE(28.4509323,77.0175083)
[OK] Sector 39: SW(28.4346743,77.0414743) NE(28.4491446,77.0581972)
[OK] Sector 77: SW(28.3632337,76.9625570) NE(28.4032337,77.0025570)
[OK] Sector 30: SW(28.4558177,77.0497732) NE(28.4687352,77.0639896)
[OK] New Colony: SW(28.4570389,77.0054286) NE(28.4736808,77.0231263)
[OK] Sector 15: SW(28.3794851,76.9096825) NE(28.3867902,76.9240718)
[OK] Sector 40: SW(28.4438734,77.0508629) NE(28.4553050,77.0640544)
[OK] Surat Nagar 1: SW(28.4819456,76.9986461) NE(28.4852155,77.0062880)
[OK] Sector 5: SW(28.3647873,76.9194192) NE(28.3722399,76.9340449)
[OK] Sector 78: SW(28.3621222,76.9613960) NE(28.3838833,76.9830167)
[OK] Sector 7 Extension: SW(28.4807712,77.0198992) NE(28.5207712,77.0598992)
[OK] Sector 9: SW(28.3799132,76.8787979) NE(28.3871405,76.8934127)
[OK] Sector 23A: SW(28.5021627,77.0362827) NE(28.5101533,77.0575714)
[OK] Mayfield garden: SW(28.4243723,77.0535539) NE(28.4286463,77.0584137)
[OK] Sector 38: SW(28.4286120,77.0336801) NE(28.4460043,77.0492887)
[OK] Sector 2: SW(28.5021117,77.0246723) NE(28.5148941,77.0417925)
[OK] Sector 95A: SW(28.4084230,76.9241277) NE(28.4207947,76.9416780)
[OK] Sector 41: SW(28.4500074,77.0559905) NE(28.4639585,77.0716604)
[OK] sector 28: SW(28.4679062,77.0715635) NE(28.4814775,77.0946320)
[OK] Southern Peripheral Road: SW(28.4019451,77.0378369) NE(28.4023980,77.0387019)
[OK] South City: SW(28.4497391,77.0512091) NE(28.4697391,77.0712091)
[OK] Sector 17: SW(28.4687352,77.0534223) NE(28.4850655,77.0704200)
[OK] Samaspur: SW(28.4068030,77.0459832) NE(28.4468030,77.0859832)
[OK] Kadarpur: SW(28.3902920,77.0556926) NE(28.3939638,77.0661074)
[OK] sector 83: SW(28.3862180,76.9608587) NE(28.4051340,76.9825179)
[OK] Pataudi Road: SW(28.3428790,76.7472376) NE(28.3528790,76.7572376)
[OK] Sector 21: SW(28.5067703,77.0664100) NE(28.5202589,77.0804111)
[OK] Sector 9A: SW(28.4634896,76.9881219) NE(28.4764407,77.0054286)
[OK] Sector 17B: SW(28.4172746,77.0910767) NE(28.4314754,77.1053206)
[OK] Chakkarpur: SW(28.4313338,77.0869961) NE(28.4723706,77.0954593)
[OK] Sector 7: SW(28.4570389,77.0054286) NE(28.4736808,77.0231263)
[OK] Ashok Vihar Phase 1: SW(28.4767161,77.0074408) NE(28.5167161,77.0474408)
[OK] Sector-5 Sohna: SW(28.2005681,77.0031377) NE(28.4465841,77.2418683)
[OK] sector 62: SW(28.3994698,77.0746581) NE(28.4173299,77.0923553)
[OK] Farrukh Nagar: SW(28.4448838,76.8193523) NE(28.4449838,76.8194523)
[OK] Sector 80: SW(28.3612242,76.9568038) NE(28.3790600,76.9664843)
[OK] Dayanand Colony: SW(28.4703674,77.0171064) NE(28.4755730,77.0249314)
[OK] Sector 17C: SW(28.4731043,77.0602131) NE(28.4745909,77.0617161)
[OK] Cyber City: SW(28.4930703,77.0842567) NE(28.5030703,77.0942567)
[OK] Patel Nagar: SW(28.4655141,77.0392443) NE(28.4656141,77.0393443)
[OK] Ramgarh: SW(28.3893131,77.0630673) NE(28.3989813,77.0687747)
[OK] Sector 64: SW(28.3714643,77.0561983) NE(28.4114643,77.0961983)
[OK] Jharsa: SW(28.4345323,77.0391372) NE(28.4545323,77.0591372)
[OK] Civil Lines: SW(28.4607321,77.0323281) NE(28.4634826,77.0354811)
[OK] Sector 10: SW(28.4358808,76.9972285) NE(28.4509323,77.0175083)
[OK] Sector 22B: SW(28.5081439,77.0655628) NE(28.5089735,77.0664426)
[OK] Gurgaon: SW(28.4890374,77.0111072) NE(28.4891374,77.0112072)
[OK] Dwarka Expressway: SW(28.4171897,76.9605926) NE(28.4337314,76.9700847)
[OK] Palam Vihar Extension: SW(28.4807712,77.0198992) NE(28.5207712,77.0598992)
[OK] Sector 1A: SW(28.2005681,76.6510198) NE(28.5409048,77.2418683)

In [6]:
rows = []

for sector, value in results.items():
  row = {
        "Sector": sector,
        "cord": value,
    }
  rows.append(row)

df = pd.DataFrame(rows)

                    Sector                                               cord
0                Sector 84  SW(28.3992344,76.9547099) NE(28.4171845,76.972...
1                Sector 81  SW(28.3810248,76.9358092) NE(28.3955282,76.956...
2               Sector 112  SW(28.5133462,77.0105771) NE(28.5348138,77.023...
3               Sector 104  SW(28.4686072,76.9808303) NE(28.4931639,77.008...
4                Sector 74  SW(28.4008281,77.0000093) NE(28.4240826,77.019...
..                     ...                                                ...
157             Sector 22B  SW(28.5081439,77.0655628) NE(28.5089735,77.066...
158                Gurgaon  SW(28.4890374,77.0111072) NE(28.4891374,77.011...
159      Dwarka Expressway  SW(28.4171897,76.9605926) NE(28.4337314,76.970...
160  Palam Vihar Extension  SW(28.4807712,77.0198992) NE(28.5207712,77.059...
161              Sector 1A  SW(28.2005681,76.6510198) NE(28.5409048,77.241...

[162 rows x 2 columns]

In [7]:
df["SW"]=df['cord'].str.split(' ').str.get(0).str.replace('SW','').str.replace('(','').str.replace(')','')
df["NE"]=df['cord'].str.split(' ').str.get(1).str.replace('NE','').str.replace('(','').str.replace(')','')

In [8]:
df.drop('cord',axis=1,inplace=True)

In [9]:
df

                    Sector                     SW                     NE
0                Sector 84  28.3992344,76.9547099  28.4171845,76.9728238
1                Sector 81  28.3810248,76.9358092  28.3955282,76.9566384
2               Sector 112  28.5133462,77.0105771  28.5348138,77.0234394
3               Sector 104  28.4686072,76.9808303  28.4931639,77.0085706
4                Sector 74  28.4008281,77.0000093  28.4240826,77.0196986
..                     ...                    ...                    ...
157             Sector 22B  28.5081439,77.0655628  28.5089735,77.0664426
158                Gurgaon  28.4890374,77.0111072  28.4891374,77.0112072
159      Dwarka Expressway  28.4171897,76.9605926  28.4337314,76.9700847
160  Palam Vihar Extension  28.4807712,77.0198992  28.5207712,77.0598992
161              Sector 1A  28.2005681,76.6510198  28.5409048,77.2418683

[162 rows x 3 columns]

In [10]:
df['NE'].str.split(',').str.get(0)

0      28.4171845
1      28.3955282
2      28.5348138
3      28.4931639
4      28.4240826
          ...
157    28.5089735
158    28.4891374
159    28.4337314
160    28.5207712
161    28.5409048
Name: NE, Length: 162, dtype: object

In [11]:
df['SW'].str.split(',').str.get(1)

0      76.9547099
1      76.9358092
2      77.0105771
3      76.9808303
4      77.0000093
          ...
157    77.0655628
158    77.0111072
159    76.9605926
160    77.0198992
161    76.6510198
Name: SW, Length: 162, dtype: object

In [12]:
df['NW']=df['NE'].str.split(',').str.get(0)+","+df['SW'].str.split(',').str.get(1)

In [13]:
df['SE']=df['SW'].str.split(',').str.get(0)+","+df['NE'].str.split(',').str.get(1)

In [14]:
df

,Sector,SW,NE,NW,SE
0,Sector 84,"28.3992344,76.9547099","28.4171845,76.9728238","28.4171845,76.9547099","28.3992344,76.9728238"
1,Sector 81,"28.3810248,76.9358092","28.3955282,76.9566384","28.3955282,76.9358092","28.3810248,76.9566384"
2,Sector 112,"28.5133462,77.0105771","28.5348138,77.0234394","28.5348138,77.0105771","28.5133462,77.0234394"
3,Sector 104,"28.4686072,76.9808303","28.4931639,77.0085706","28.4931639,76.9808303","28.4686072,77.0085706"
4,Sector 74,"28.4008281,77.0000093","28.4240826,77.0196986","28.4240826,77.0000093","28.4008281,77.0196986"
...,...,...,...,...,...
157,Sector 22B,"28.5081439,77.0655628","28.5089735,77.0664426","28.5089735,77.0655628","28.5081439,77.0664426"
158,Gurgaon,"28.4890374,77.0111072","28.4891374,77.0112072","28.4891374,77.0111072","28.4890374,77.0112072"
159,Dwarka Expressway,"28.4171897,76.9605926","28.4337314,76.9700847","28.4337314,76.9605926","28.4171897,76.9700847"
160,Palam Vihar Extension,"28.4807712,77.0198992","28.5207712,77.0598992","28.5207712,77.0198992","28.4807712,77.0598992"
161,Sector 1A,"28.2005681,76.6510198","28.5409048,77.2418683","28.5409048,76.6510198","28.2005681,77.2418683"

In [29]:
df.to_csv("loc.csv")